INSERT INTO organizations (codigo, secretaria, sigla, classificacao) VALUES
(1, 'Casa Civil do Município de Palmas', 'CACIVIL', 'DIRETA'),
(5, 'Gabinete do Prefeito', 'GAP', 'DIRETA'),
(6, 'Gabinete do Vice-Prefeito', 'GAVIP', 'DIRETA'),
(7, 'Guarda Metropolitana de Palmas', 'GMP', 'DIRETA'),
(9, 'Secretária Municipal Extraordinário de Representação em Brasília', 'SERB', 'DIRETA'),
(12, 'Secretária Municipal Extraordinário de Articulação Comunitária', 'SEMAC', 'DIRETA'),
(14, 'Secretária Municipal Extraordinário de Igualdade Racial e Direitos Humanos', 'SMPIR', 'DIRETA'),
(15, 'Secretária Municipal Extraordinário da Região Metropolitana', 'SEMRP', 'DIRETA'),
(16, 'Procuradoria-Geral do Município', 'PGM', 'DIRETA'),
(17, 'Secretaria Municipal de Comunicação', 'SECOMP', 'DIRETA'),
(18, 'Secretaria Municipal de Governo', 'SEGOP', 'DIRETA'),
(19, 'Controladoria-Geral do Município', 'CGMP', 'DIRETA'),
(20, 'Secretaria Municipal de Administração e Modernização', 'SECAM', 'DIRETA'),
(21, 'Secretaria Municipal de Finanças', 'SECMUFI', 'DIRETA'),
(23, 'Secretaria Municipal de Planejamento, Orçamento e Licitações', 'SEPLAM', 'DIRETA'),
(24, 'Secretaria Municipal da Mulher', 'SMP', 'DIRETA'),
(26, 'Secretaria Municipal de Ação Social', 'SMAS', 'DIRETA'),
(29, 'Secretaria Municipal de Agricultura e Serviços do Interior', 'SAGRIP', 'DIRETA'),
(30, 'Secretaria Municipal de Desenvolvimento Econômico e Empreendedorismo', 'SECDEP', 'DIRETA'),
(33, 'Secretaria Municipal de Desenvolvimento Urbano e Regularização Fundiária', 'SECDURP', 'DIRETA'),
(34, 'Secretaria Municipal de Educação', 'SEDUCP', 'DIRETA'),
(38, 'Secretaria Municipal de Habitação', 'SEMUHP', 'DIRETA'),
(40, 'Secretaria Municipal de Infraestrutura e Obras Públicas', 'SEINFRAP', 'DIRETA'),
(43, 'Secretaria Municipal de Mobilidade Urbana e Defesa Civil', 'SECMOP', 'DIRETA'),
(45, 'Secretaria Municipal de Planejamento Urbano', 'SEPLAP', 'DIRETA'),
(46, 'Secretaria Municipal de Proteção e Bem-Estar Animal', 'SECBEAP', 'DIRETA'),
(47, 'Secretaria Municipal de Saúde', 'SESAUP', 'DIRETA'),
(48, 'Secretaria Municipal de Zeladoria Urbana', 'SEZU', 'DIRETA'),
(49, 'Agência de Regulação, Controle e Fiscalização de Serviços Públicos', 'ARP', 'INDIRETA'),
(55, 'Agência de Tecnologia da Informação de Palmas', 'AGTEC', 'INDIRETA'),
(56, 'Agência de Transporte Coletivo de Palmas', 'ATCP', 'INDIRETA'),
(57, 'Agência Municipal de Turismo', 'AGTUR', 'INDIRETA'),
(60, 'Fundação Cultural de Palmas', 'FCP', 'INDIRETA'),
(61, 'Fundação Escola de Saúde Pública de Palmas', 'FESP', 'INDIRETA'),
(62, 'Fundação Municipal de Esportes e Lazer de Palmas', 'FUNDESPORTES', 'INDIRETA'),
(63, 'Fundação Municipal da Juventude de Palmas', 'FJP', 'INDIRETA'),
(64, 'Fundação Municipal de Meio Ambiente de Palmas', 'FMA', 'INDIRETA'),
(65, 'Instituto de Previdência Social do Município de Palmas', 'PREVIPALMAS', 'INDIRETA');
