INSERT INTO organizations (codigo, secretaria, sigla, classificacao) VALUES
(1, 'Secretaria Executiva da Governadoria', 'SEGOV', 'DIRETA'),
(3, 'Casa Civil', 'CACIV', 'DIRETA'),
(5, 'Casa Militar', 'CAMIL', 'DIRETA'),
(6, 'Controladoria-Geral do Estado', 'CGE', 'DIRETA'),
(7, 'Secretaria da Comunicação', 'SECOM', 'DIRETA'),
(9, 'Procuradoria-Geral do Estado', 'PGE', 'DIRETA'),
(12, 'Polícia Militar do Estado do Tocantins', 'PMTO', 'DIRETA'),
(14, 'Corpo de Bombeiros Militar do Estado do Tocantins', 'CBMTO', 'DIRETA'),
(15, 'Secretaria da Fazenda', 'SEFAZ', 'DIRETA'),
(16, 'Secretaria da Administração', 'SECAD', 'DIRETA'),
(17, 'Secretaria da Saúde', 'SESAU', 'DIRETA'),
(18, 'Secretaria da Educação', 'SEDUC', 'DIRETA'),
(19, 'Secretaria da Segurança Pública', 'SSP', 'DIRETA'),
(20, 'Secretaria da Agricultura e Pecuária', 'SEAP', 'DIRETA'),
(21, 'Secretaria da Indústria, Comércio e Serviços', 'SEINCOM', 'DIRETA'),
(23, 'Secretaria do Meio Ambiente e Recursos Hídricos', 'SEMARH', 'DIRETA'),
(24, 'Secretaria das Cidades, Habitação e Desenvolvimento Regional', 'SCIDADES', 'DIRETA'),
(26, 'Secretaria do Trabalho e Desenvolvimento Social', 'SETAS', 'DIRETA'),
(29, 'Secretaria da Cidadania e Justiça', 'SECIJU', 'DIRETA'),
(30, 'Agência de Mineração do Estado do Tocantins', 'AMETO', 'INDIRETA'),
(33, 'Departamento Estadual de Trânsito', 'DETRAN/TO', 'INDIRETA'),
(34, 'Instituto de Terras do Estado do Tocantins', 'ITERTINS', 'INDIRETA'),
(38, 'Instituto Natureza do Tocantins', 'NATURATINS', 'INDIRETA'),
(40, 'Agência de Tecnologia da Informação', 'ATI-TO', 'INDIRETA'),
(43, 'Instituto de Gestão Previdenciária do Estado do Tocantins', 'IGEPREV-TOCANTINS', 'INDIRETA'),
(45, 'Agência de Defesa Agropecuária do Estado do Tocantins', 'ADAPEC-TOCANTINS', 'INDIRETA'),
(46, 'Instituto de Desenvolvimento Rural do Estado do Tocantins', 'RURALTINS', 'INDIRETA'),
(47, 'Fundação de Amparo à Pesquisa do Estado do Tocantins', 'FAPT', 'INDIRETA'),
(48, 'Agência de Metrologia, Avaliação da Conformidade, Inovação e Tecnologia do Estado do Tocantins', 'AEM', 'INDIRETA'),
(49, 'Junta Comercial do Estado do Tocantins', 'JUCETINS', 'INDIRETA'),
(55, 'Agência de Transportes, Obras e Infraestrutura', 'AGETO', 'INDIRETA'),
(56, 'Agência Tocantinense de Regulação, Controle e Fiscalização de Serviços Públicos', 'ATR', 'INDIRETA'),
(57, 'Agência Tocantinense de Saneamento', 'ATS', 'INDIRETA'),
(60, 'Secretaria de Parcerias e Investimentos', 'SPI', 'DIRETA'),
(61, 'Secretaria do Planejamento e Orçamento', 'SEPLAN', 'DIRETA'),
(62, 'Secretaria dos Esportes e Juventude', 'SEJU', 'DIRETA'),
(63, 'Secretaria da Cultura', 'SECUT', 'DIRETA'),
(64, 'Secretaria da Mulher', 'SDM', 'DIRETA'),
(65, 'Secretaria dos Povos Originários e Tradicionais', 'SEPOT', 'DIRETA'),
(66, 'Secretaria da Pesca e Aquicultura', 'SEPAQ', 'DIRETA'),
(67, 'Secretaria do Turismo', 'SECTUR', 'DIRETA'),
(68, 'Secretaria da Igualdade Racial', 'SECRI', 'DIRETA'),
(69, 'Secretaria de Assuntos Institucionais', 'SACAI', 'DIRETA');